import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Link2, MessageSquare, Search, ShieldCheck, Share2, Sparkles } from "lucide-react";
import { PageShell } from "@/components/page-shell";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/movie-adaptation")({
  staticData: { sitemap: true },
  head: () => ({ links: [{ rel: "canonical", href: "https://fourthgroupco.lovable.app/movie-adaptation" }], meta: [{ title: "Book-to-Screen Pitching | Fourth Group & Co" }, { name: "description", content: "Create an adaptation-ready story pitch, retain control of your work and make it discoverable to film and television readers." }, { property: "og:title", content: "Book-to-Screen Pitching | Fourth Group & Co" }, { property: "og:description", content: "A clear, rights-aware route from story to screen pitch." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:url", content: "https://fourthgroupco.lovable.app/movie-adaptation" }] }),
  component: MovieAdaptationPage,
});

const BENEFITS = [
  { icon: ShieldCheck, title: "Keep control", text: "You choose what appears publicly and which rights remain available." },
  { icon: Link2, title: "A clear pitch page", text: "Present the logline, genre, format and rights information in one readable place." },
  { icon: MessageSquare, title: "Direct conversations", text: "Interested readers can discuss the work with the rights holder without Fourth Group taking ownership." },
  { icon: Search, title: "Be discoverable", text: "Published pitches can be searched by title, format, genre and story premise." },
  { icon: Share2, title: "Share your work", text: "Use your pitch as a focused introduction when approaching collaborators and representatives." },
  { icon: Sparkles, title: "Editorial clarity", text: "A guided structure helps you explain the story’s hook, audience and screen potential." },
];

function MovieAdaptationPage() {
  return <PageShell>
    <section className="bg-secondary text-secondary-foreground"><div className="mx-auto max-w-5xl px-5 py-20 text-center md:py-28"><p className="text-xs font-semibold uppercase text-primary">Movie adaptation</p><h1 className="mx-auto mt-5 max-w-4xl font-serif text-4xl leading-tight md:text-6xl">Help the right reader see your story on screen</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-secondary-foreground/70">Writers build focused adaptation pitches. Producers, agents and publishing professionals can search the public library and make contact directly.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild><Link to="/create-pitch">Create your pitch <ArrowRight className="size-4"/></Link></Button><Button asChild variant="outline" className="border-secondary-foreground/30 bg-transparent text-secondary-foreground hover:bg-secondary-foreground/10 hover:text-secondary-foreground"><Link to="/search-pitches">Browse pitches</Link></Button><Button asChild variant="outline" className="border-primary/50 bg-transparent text-primary hover:bg-primary/10 hover:text-primary"><Link to="/pitch-plans">See plans</Link></Button></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-16 md:py-20"><div className="text-center"><h2 className="font-serif text-3xl md:text-4xl">Everything a pitch needs to travel</h2><p className="mt-3 text-muted-foreground">Built for working writers and careful industry readers.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{BENEFITS.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-md border border-border bg-card p-6"><Icon className="size-5 text-primary"/><h3 className="mt-5 font-serif text-xl">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></article>)}</div></section>
    <section className="border-y border-border bg-muted"><div className="mx-auto max-w-6xl px-5 py-16 md:py-20"><h2 className="text-center font-serif text-3xl">How it works</h2><ol className="mt-9 grid gap-4 md:grid-cols-4">{[["01", "Choose a plan", "Select the level of editorial and listing support your work needs."], ["02", "Build your pitch", "Add the title, logline, genre, format, synopsis and rights position."], ["03", "Choose visibility", "Keep the pitch private or publish it to the searchable library."], ["04", "Respond directly", "Handle genuine enquiries on your own terms and keep control of every decision."]].map(([n, title, text]) => <li key={n} className="rounded-md border border-border bg-card p-5"><span className="font-serif text-2xl text-primary">{n}</span><h3 className="mt-5 font-serif text-lg">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></li>)}</ol></div></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-2 md:py-20"><div><p className="text-xs font-semibold uppercase text-primary">For industry readers</p><h2 className="mt-3 font-serif text-3xl">Find stories with clear rights information</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Search concise pitches without asking writers for a full manuscript first. Each listing shows its format, genre, premise and the rights position supplied by the author.</p><ul className="mt-6 space-y-3 text-sm">{["Search public pitches anonymously", "Compare format and genre quickly", "See whether adaptation rights are available", "Contact the writer or representative directly"].map((item) => <li key={item} className="flex gap-2"><Check className="mt-0.5 size-4 text-primary"/>{item}</li>)}</ul><Button asChild className="mt-7"><Link to="/search-pitches">Search the pitch library</Link></Button></div><div className="rounded-md border border-border bg-card p-7"><p className="text-xs font-semibold uppercase text-primary">For writers</p><h2 className="mt-3 font-serif text-3xl">A professional home for the screen version of your story</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Your pitch remains yours. Fourth Group provides the structure and visibility; it does not take commission, acquire rights or sit inside your conversations.</p><Button asChild variant="outline" className="mt-7"><Link to="/pitch-plans">Compare writer plans</Link></Button></div></section>
  </PageShell>;
}