import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, CircleHelp, ShieldCheck } from "lucide-react";
import { PageShell } from "@/components/page-shell";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/pitch-plans")({
  staticData: { sitemap: true },
  head: () => ({ links: [{ rel: "canonical", href: "https://fourthgroupco.lovable.app/pitch-plans" }], meta: [{ title: "Pitch Plans & Pricing | Fourth Group & Co" }, { name: "description", content: "Compare annual writer and industry plans for creating, publishing and searching adaptation-ready story pitches." }, { property: "og:title", content: "Pitch Plans & Pricing | Fourth Group & Co" }, { property: "og:description", content: "Straightforward annual pricing with no commission on adaptation deals." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:url", content: "https://fourthgroupco.lovable.app/pitch-plans" }] }),
  component: PitchPlansPage,
});

const PLANS = [
  { name: "Single Story", audience: "For one focused project", price: "$145", features: ["One pitch for 12 months", "Public or private visibility", "Direct enquiries", "Printable pitch summary"] },
  { name: "Working Writer", audience: "For a growing catalogue", price: "$245", featured: true, features: ["Up to five pitches", "Everything in Single Story", "Pitch editing tools", "Priority catalogue placement"] },
  { name: "Editorial Plus", audience: "For deeper pitch development", price: "$395", features: ["Up to ten pitches", "Everything in Working Writer", "One editorial review", "Priority support"] },
  { name: "Complete Slate", audience: "For an active rights list", price: "$645", features: ["Up to ten pitches", "Producer consultation", "Editorial polish", "Featured slate placement"] },
];
const FAQ = [["What is a pitch package?", "A focused presentation of the title, logline, format, genre, synopsis and rights position. It helps a reader assess the story before requesting longer material."], ["Does Fourth Group take commission?", "No. If a reader options or acquires a story, the agreement remains between the rights holder and that reader or their representatives."], ["How long does a plan last?", "Each listed plan covers twelve months from purchase. You can edit your active pitches during that period."], ["Can I change plans later?", "Yes. Contact us and we will help move an active account to the most suitable level."], ["Is payment available now?", "Not yet. These are the planned annual rates. Account creation and pitch drafting are available while checkout is being prepared."], ["Do you guarantee industry contact?", "No. The service improves presentation and discoverability, but no legitimate platform can guarantee a deal or response."]];

function PitchPlansPage() {
  return <PageShell>
    <section className="bg-secondary text-secondary-foreground"><div className="mx-auto max-w-4xl px-5 py-20 text-center"><p className="text-xs font-semibold uppercase text-primary">Plans and pricing</p><h1 className="mt-4 font-serif text-4xl md:text-5xl">Clear annual plans. No commission.</h1><p className="mx-auto mt-5 max-w-2xl text-secondary-foreground/70">Choose how many stories you want to present. Your rights remain yours, and no hidden charge is added to a successful introduction.</p></div></section>
    <section className="mx-auto max-w-6xl px-5 py-16 md:py-20"><h2 className="text-center font-serif text-3xl">For writers</h2><p className="mt-3 text-center text-sm text-muted-foreground">Every plan is annual. Prices below are in US dollars.</p><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{PLANS.map((plan) => <article key={plan.name} className={plan.featured ? "flex flex-col rounded-md border-2 border-primary bg-card p-6 shadow-md" : "flex flex-col rounded-md border border-border bg-card p-6"}>{plan.featured ? <span className="mb-4 w-fit rounded-sm bg-primary px-2 py-1 text-[10px] font-bold uppercase text-primary-foreground">Most popular</span> : null}<h3 className="font-serif text-2xl">{plan.name}</h3><p className="mt-1 min-h-10 text-xs text-muted-foreground">{plan.audience}</p><p className="mt-5 font-serif text-4xl">{plan.price}<span className="font-sans text-xs text-muted-foreground"> / year</span></p><ul className="my-6 flex-1 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex gap-2 text-sm text-muted-foreground"><Check className="mt-0.5 size-4 shrink-0 text-primary"/>{feature}</li>)}</ul><Button asChild variant={plan.featured ? "default" : "outline"}><Link to="/create-pitch">Start with {plan.name}</Link></Button></article>)}</div><p className="mt-5 text-center text-xs text-muted-foreground">Checkout is not active yet. Creating an account starts your pitch draft without charging you.</p></section>
    <section className="border-y border-border bg-muted"><div className="mx-auto max-w-4xl px-5 py-16"><h2 className="text-center font-serif text-3xl">For producers, agents and publishers</h2><div className="mt-9 grid gap-5 md:grid-cols-2"><article className="rounded-md border border-primary bg-card p-7"><h3 className="font-serif text-2xl">Industry access</h3><p className="mt-2 text-sm text-muted-foreground">For screen professionals and publishing-rights teams.</p><p className="mt-6 font-serif text-4xl">$145<span className="font-sans text-xs text-muted-foreground"> / year</span></p><ul className="mt-6 space-y-3 text-sm text-muted-foreground">{["Search the pitch library", "Save an unlimited shortlist", "Contact rights holders directly", "Keep searches private"].map((item) => <li key={item} className="flex gap-2"><Check className="size-4 text-primary"/>{item}</li>)}</ul><Button asChild className="mt-7 w-full"><Link to="/auth" search={{ redirect: "/search-pitches" }}>Create an industry account</Link></Button></article><article className="rounded-md border border-border bg-card p-7"><ShieldCheck className="size-6 text-primary"/><h3 className="mt-4 font-serif text-2xl">What you get from day one</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Build a profile, search by format and genre, and review the rights information supplied by each writer. Fourth Group does not enter negotiations or take a share of any deal.</p><Button asChild variant="outline" className="mt-7 w-full"><Link to="/search-pitches">Preview the library</Link></Button></article></div></div></section>
    <section className="mx-auto max-w-5xl px-5 py-16 md:py-20"><h2 className="text-center font-serif text-3xl">Questions writers ask</h2><div className="mt-9 grid gap-4 md:grid-cols-2">{FAQ.map(([q, a]) => <article key={q} className="rounded-md border border-border bg-card p-6"><CircleHelp className="size-5 text-primary"/><h3 className="mt-3 font-serif text-lg">{q}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{a}</p></article>)}</div><div className="mt-9 text-center"><Button asChild><Link to="/contact">Ask us a question</Link></Button></div></section>
  </PageShell>;
}