import { createFileRoute, Link } from "@tanstack/react-router";
import { BookOpen, Clock3, Feather, Send } from "lucide-react";
import { PageShell } from "@/components/page-shell";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/short-stories")({
  staticData: { sitemap: true },
  head: () => ({ links: [{ rel: "canonical", href: "https://fourthgroupco.lovable.app/short-stories" }], meta: [{ title: "Short Stories & Submission Guidance | Fourth Group & Co" }, { name: "description", content: "Read original short fiction and find practical guidance for preparing and submitting your own stories." }, { property: "og:title", content: "Short Stories & Submission Guidance | Fourth Group & Co" }, { property: "og:description", content: "Original fiction, close reading and practical submission guidance." }, { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:url", content: "https://fourthgroupco.lovable.app/short-stories" }] }),
  component: ShortStoriesPage,
});

function ShortStoriesPage() {
  return <PageShell>
    <header className="border-b border-border bg-card"><div className="mx-auto max-w-3xl px-5 py-14 text-center md:py-20"><p className="text-xs font-semibold uppercase text-primary">Fourth Group fiction</p><h1 className="mt-3 font-serif text-4xl md:text-5xl">Short stories</h1><p className="mx-auto mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground">A reading room for original work, alongside practical routes for writers preparing their own fiction for publication.</p></div></header>
    <section className="mx-auto max-w-4xl px-5 py-12 md:py-16">
      <div className="grid gap-8 md:grid-cols-[1fr_18rem]"><div><h2 className="font-serif text-3xl">Every story deserves close attention</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">We value stories that know what they are trying to do, whether they arrive in a page or stretch across twenty. Before submitting anywhere, read the publication, revise beyond the first clean draft and keep a clear record of the rights you grant.</p></div><aside className="rounded-md border border-border bg-accent p-5"><Clock3 className="size-5 text-primary"/><p className="mt-3 font-serif text-lg">Before you submit</p><ul className="mt-3 space-y-2 text-sm text-muted-foreground"><li>Confirm the word limit</li><li>Check simultaneous-submission rules</li><li>Use the requested file format</li><li>Record the response window</li></ul></aside></div>
      <h2 className="mt-14 text-center font-serif text-2xl">Ways to take part</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><article className="rounded-md border border-border bg-card p-6"><Send className="size-5 text-primary"/><h3 className="mt-4 font-serif text-xl">Find a suitable magazine</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Use the magazine directory to compare genres, reading periods, payment and response times before submitting.</p><Button asChild variant="outline" className="mt-5"><Link to="/literary-magazines">Browse magazines</Link></Button></article><article className="rounded-md border border-border bg-card p-6"><Feather className="size-5 text-primary"/><h3 className="mt-4 font-serif text-xl">Enter a competition</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Compare current fiction competitions, including free opportunities and prizes for emerging writers.</p><Button asChild variant="outline" className="mt-5"><Link to="/contests">Browse contests</Link></Button></article></div>
    </section>
    <article className="border-y border-border bg-card"><div className="mx-auto max-w-3xl px-5 py-14 md:py-20"><div className="flex items-center gap-3 text-xs font-semibold uppercase text-primary"><BookOpen className="size-4"/>Featured original fiction</div><h2 className="mt-4 font-serif text-4xl">The Last Light in the Reading Room</h2><p className="mt-2 text-sm text-muted-foreground">A short story by Adaeze Okonkwo · 8 minute read</p>
      <div className="mt-10 space-y-6 font-serif text-lg leading-8 text-foreground/90"><p>The library kept one lamp burning after closing. It stood at the end of the long oak table, beside the chair nobody chose in daylight, and cast a green pool over the scratched wood. Mara had been asked to switch it off. Every evening she walked towards it with the key ring pressed into her palm, and every evening someone appeared beneath it.</p><p>The first was a boy revising a letter. He folded and unfolded the page until the creases went soft. The second was an old woman reading the same paragraph of a gardening book. Then came a man with rain on his shoulders and no book at all. None of them spoke. At nine fifteen, when Mara cleared her throat, they gathered their things and left through the brass doors.</p><p>On Thursday the chair was empty. A cream envelope waited in its place, addressed in the narrow handwriting of Mara’s mother, dead eleven years. She did not open it. She sat beneath the green lamp and listened to the building settle: pipes ticking, shelves giving small wooden sighs, the city pressing weather against the windows.</p><p>Inside the envelope was no revelation, only a list. Return the blue bowl to Ruth. Water the fern on Sundays. Do not let Mara think leaving means she has failed. The final line had been underlined twice.</p><p>Mara read it until the words stopped behaving like instructions and became a voice. Then she laughed, loudly enough to startle herself. The sound moved through the empty room and came back warmer.</p><p>At nine fifteen she left the lamp burning. In the morning, a young woman was asleep at the table with a manuscript under her cheek. Mara placed a note beside her: Take your time. The room is open.</p></div>
      <div className="mt-12 flex flex-wrap items-center justify-between gap-4 border-t border-border pt-6"><p className="text-sm text-muted-foreground">Looking for a place to send your own work?</p><Button asChild><Link to="/literary-magazines">Explore publications</Link></Button></div>
    </div></article>
  </PageShell>;
}