/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthorServicesRouteImport } from './routes/author-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as CraftPracticeRouteImport } from './routes/craft-practice'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GrantsAwardsRouteImport } from './routes/grants-awards'
import { Route as LiteraryAgentsRouteImport } from './routes/literary-agents'
import { Route as LiteraryMagazinesRouteImport } from './routes/literary-magazines'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MovieAdaptationRouteImport } from './routes/movie-adaptation'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PitchPlansRouteImport } from './routes/pitch-plans'
import { Route as ResidenciesRouteImport } from './routes/residencies'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RightAgentRouteImport } from './routes/right-agent'
import { Route as SearchPitchesRouteImport } from './routes/search-pitches'
import { Route as ShortStoriesRouteImport } from './routes/short-stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SmallPressesRouteImport } from './routes/small-presses'
import { Route as WritingPromptsRouteImport } from './routes/writing-prompts'
import { Route as AuthenticatedCreatePitchRouteImport } from './routes/_authenticated/create-pitch'
import { Route as AuthenticatedPitchDashboardRouteImport } from './routes/_authenticated/pitch-dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorServicesRoute = AuthorServicesRouteImport.update({
  id: '/author-services',
  path: '/author-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftPracticeRoute = CraftPracticeRouteImport.update({
  id: '/craft-practice',
  path: '/craft-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsAwardsRoute = GrantsAwardsRouteImport.update({
  id: '/grants-awards',
  path: '/grants-awards',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteraryAgentsRoute = LiteraryAgentsRouteImport.update({
  id: '/literary-agents',
  path: '/literary-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteraryMagazinesRoute = LiteraryMagazinesRouteImport.update({
  id: '/literary-magazines',
  path: '/literary-magazines',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieAdaptationRoute = MovieAdaptationRouteImport.update({
  id: '/movie-adaptation',
  path: '/movie-adaptation',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchPlansRoute = PitchPlansRouteImport.update({
  id: '/pitch-plans',
  path: '/pitch-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenciesRoute = ResidenciesRouteImport.update({
  id: '/residencies',
  path: '/residencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RightAgentRoute = RightAgentRouteImport.update({
  id: '/right-agent',
  path: '/right-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchPitchesRoute = SearchPitchesRouteImport.update({
  id: '/search-pitches',
  path: '/search-pitches',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortStoriesRoute = ShortStoriesRouteImport.update({
  id: '/short-stories',
  path: '/short-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SmallPressesRoute = SmallPressesRouteImport.update({
  id: '/small-presses',
  path: '/small-presses',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingPromptsRoute = WritingPromptsRouteImport.update({
  id: '/writing-prompts',
  path: '/writing-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreatePitchRoute =
  AuthenticatedCreatePitchRouteImport.update({
    id: '/create-pitch',
    path: '/create-pitch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPitchDashboardRoute =
  AuthenticatedPitchDashboardRouteImport.update({
    id: '/pitch-dashboard',
    path: '/pitch-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/author-services': typeof AuthorServicesRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/craft-practice': typeof CraftPracticeRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/grants-awards': typeof GrantsAwardsRoute
  '/literary-agents': typeof LiteraryAgentsRoute
  '/literary-magazines': typeof LiteraryMagazinesRoute
  '/membership': typeof MembershipRoute
  '/movie-adaptation': typeof MovieAdaptationRoute
  '/news': typeof NewsRoute
  '/pitch-plans': typeof PitchPlansRoute
  '/residencies': typeof ResidenciesRoute
  '/resources': typeof ResourcesRoute
  '/right-agent': typeof RightAgentRoute
  '/search-pitches': typeof SearchPitchesRoute
  '/short-stories': typeof ShortStoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-presses': typeof SmallPressesRoute
  '/writing-prompts': typeof WritingPromptsRoute
  '/create-pitch': typeof AuthenticatedCreatePitchRoute
  '/pitch-dashboard': typeof AuthenticatedPitchDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/author-services': typeof AuthorServicesRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/craft-practice': typeof CraftPracticeRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/grants-awards': typeof GrantsAwardsRoute
  '/literary-agents': typeof LiteraryAgentsRoute
  '/literary-magazines': typeof LiteraryMagazinesRoute
  '/membership': typeof MembershipRoute
  '/movie-adaptation': typeof MovieAdaptationRoute
  '/news': typeof NewsRoute
  '/pitch-plans': typeof PitchPlansRoute
  '/residencies': typeof ResidenciesRoute
  '/resources': typeof ResourcesRoute
  '/right-agent': typeof RightAgentRoute
  '/search-pitches': typeof SearchPitchesRoute
  '/short-stories': typeof ShortStoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-presses': typeof SmallPressesRoute
  '/writing-prompts': typeof WritingPromptsRoute
  '/create-pitch': typeof AuthenticatedCreatePitchRoute
  '/pitch-dashboard': typeof AuthenticatedPitchDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/author-services': typeof AuthorServicesRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/craft-practice': typeof CraftPracticeRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/grants-awards': typeof GrantsAwardsRoute
  '/literary-agents': typeof LiteraryAgentsRoute
  '/literary-magazines': typeof LiteraryMagazinesRoute
  '/membership': typeof MembershipRoute
  '/movie-adaptation': typeof MovieAdaptationRoute
  '/news': typeof NewsRoute
  '/pitch-plans': typeof PitchPlansRoute
  '/residencies': typeof ResidenciesRoute
  '/resources': typeof ResourcesRoute
  '/right-agent': typeof RightAgentRoute
  '/search-pitches': typeof SearchPitchesRoute
  '/short-stories': typeof ShortStoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-presses': typeof SmallPressesRoute
  '/writing-prompts': typeof WritingPromptsRoute
  '/_authenticated/create-pitch': typeof AuthenticatedCreatePitchRoute
  '/_authenticated/pitch-dashboard': typeof AuthenticatedPitchDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/author-services'
    | '/contact'
    | '/contests'
    | '/craft-practice'
    | '/directory'
    | '/events'
    | '/grants-awards'
    | '/literary-agents'
    | '/literary-magazines'
    | '/membership'
    | '/movie-adaptation'
    | '/news'
    | '/pitch-plans'
    | '/residencies'
    | '/resources'
    | '/right-agent'
    | '/search-pitches'
    | '/short-stories'
    | '/sitemap.xml'
    | '/small-presses'
    | '/writing-prompts'
    | '/create-pitch'
    | '/pitch-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/author-services'
    | '/contact'
    | '/contests'
    | '/craft-practice'
    | '/directory'
    | '/events'
    | '/grants-awards'
    | '/literary-agents'
    | '/literary-magazines'
    | '/membership'
    | '/movie-adaptation'
    | '/news'
    | '/pitch-plans'
    | '/residencies'
    | '/resources'
    | '/right-agent'
    | '/search-pitches'
    | '/short-stories'
    | '/sitemap.xml'
    | '/small-presses'
    | '/writing-prompts'
    | '/create-pitch'
    | '/pitch-dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/author-services'
    | '/contact'
    | '/contests'
    | '/craft-practice'
    | '/directory'
    | '/events'
    | '/grants-awards'
    | '/literary-agents'
    | '/literary-magazines'
    | '/membership'
    | '/movie-adaptation'
    | '/news'
    | '/pitch-plans'
    | '/residencies'
    | '/resources'
    | '/right-agent'
    | '/search-pitches'
    | '/short-stories'
    | '/sitemap.xml'
    | '/small-presses'
    | '/writing-prompts'
    | '/_authenticated/create-pitch'
    | '/_authenticated/pitch-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AuthorServicesRoute: typeof AuthorServicesRoute
  ContactRoute: typeof ContactRoute
  ContestsRoute: typeof ContestsRoute
  CraftPracticeRoute: typeof CraftPracticeRoute
  DirectoryRoute: typeof DirectoryRoute
  EventsRoute: typeof EventsRoute
  GrantsAwardsRoute: typeof GrantsAwardsRoute
  LiteraryAgentsRoute: typeof LiteraryAgentsRoute
  LiteraryMagazinesRoute: typeof LiteraryMagazinesRoute
  MembershipRoute: typeof MembershipRoute
  MovieAdaptationRoute: typeof MovieAdaptationRoute
  NewsRoute: typeof NewsRoute
  PitchPlansRoute: typeof PitchPlansRoute
  ResidenciesRoute: typeof ResidenciesRoute
  ResourcesRoute: typeof ResourcesRoute
  RightAgentRoute: typeof RightAgentRoute
  SearchPitchesRoute: typeof SearchPitchesRoute
  ShortStoriesRoute: typeof ShortStoriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmallPressesRoute: typeof SmallPressesRoute
  WritingPromptsRoute: typeof WritingPromptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-services': {
      id: '/author-services'
      path: '/author-services'
      fullPath: '/author-services'
      preLoaderRoute: typeof AuthorServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft-practice': {
      id: '/craft-practice'
      path: '/craft-practice'
      fullPath: '/craft-practice'
      preLoaderRoute: typeof CraftPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants-awards': {
      id: '/grants-awards'
      path: '/grants-awards'
      fullPath: '/grants-awards'
      preLoaderRoute: typeof GrantsAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literary-agents': {
      id: '/literary-agents'
      path: '/literary-agents'
      fullPath: '/literary-agents'
      preLoaderRoute: typeof LiteraryAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literary-magazines': {
      id: '/literary-magazines'
      path: '/literary-magazines'
      fullPath: '/literary-magazines'
      preLoaderRoute: typeof LiteraryMagazinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie-adaptation': {
      id: '/movie-adaptation'
      path: '/movie-adaptation'
      fullPath: '/movie-adaptation'
      preLoaderRoute: typeof MovieAdaptationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch-plans': {
      id: '/pitch-plans'
      path: '/pitch-plans'
      fullPath: '/pitch-plans'
      preLoaderRoute: typeof PitchPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residencies': {
      id: '/residencies'
      path: '/residencies'
      fullPath: '/residencies'
      preLoaderRoute: typeof ResidenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/right-agent': {
      id: '/right-agent'
      path: '/right-agent'
      fullPath: '/right-agent'
      preLoaderRoute: typeof RightAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-pitches': {
      id: '/search-pitches'
      path: '/search-pitches'
      fullPath: '/search-pitches'
      preLoaderRoute: typeof SearchPitchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-stories': {
      id: '/short-stories'
      path: '/short-stories'
      fullPath: '/short-stories'
      preLoaderRoute: typeof ShortStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/small-presses': {
      id: '/small-presses'
      path: '/small-presses'
      fullPath: '/small-presses'
      preLoaderRoute: typeof SmallPressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing-prompts': {
      id: '/writing-prompts'
      path: '/writing-prompts'
      fullPath: '/writing-prompts'
      preLoaderRoute: typeof WritingPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create-pitch': {
      id: '/_authenticated/create-pitch'
      path: '/create-pitch'
      fullPath: '/create-pitch'
      preLoaderRoute: typeof AuthenticatedCreatePitchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitch-dashboard': {
      id: '/_authenticated/pitch-dashboard'
      path: '/pitch-dashboard'
      fullPath: '/pitch-dashboard'
      preLoaderRoute: typeof AuthenticatedPitchDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreatePitchRoute: typeof AuthenticatedCreatePitchRoute
  AuthenticatedPitchDashboardRoute: typeof AuthenticatedPitchDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreatePitchRoute: AuthenticatedCreatePitchRoute,
  AuthenticatedPitchDashboardRoute: AuthenticatedPitchDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AuthorServicesRoute: AuthorServicesRoute,
  ContactRoute: ContactRoute,
  ContestsRoute: ContestsRoute,
  CraftPracticeRoute: CraftPracticeRoute,
  DirectoryRoute: DirectoryRoute,
  EventsRoute: EventsRoute,
  GrantsAwardsRoute: GrantsAwardsRoute,
  LiteraryAgentsRoute: LiteraryAgentsRoute,
  LiteraryMagazinesRoute: LiteraryMagazinesRoute,
  MembershipRoute: MembershipRoute,
  MovieAdaptationRoute: MovieAdaptationRoute,
  NewsRoute: NewsRoute,
  PitchPlansRoute: PitchPlansRoute,
  ResidenciesRoute: ResidenciesRoute,
  ResourcesRoute: ResourcesRoute,
  RightAgentRoute: RightAgentRoute,
  SearchPitchesRoute: SearchPitchesRoute,
  ShortStoriesRoute: ShortStoriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmallPressesRoute: SmallPressesRoute,
  WritingPromptsRoute: WritingPromptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
